### PR TITLE
Add AdiIRC and IRC for Android to list of clients

### PR DESCRIPTION
**Pull request by RogueScholar**
Two very worthy additions in my opinion plus a little window dressing

### CODE REVIEW

**Comment by DanielOaks** [comment]
Just curious, what's with the new LICENSE file being added? The readme says _"Copyright © 2016+ Craig Davison. Licensed under CC0 1.0."_, [CC0](https://creativecommons.org/publicdomain/zero/1.0/) isn't BSD-3-Clause.

**Comment by DanielOaks** [comment]
Outside the license file, nice changes. Using those icons for the clients is an interesting move.

**Comment by RogueScholar** [comment]
Oh, I do a fair bit of editing on Wikipedia and one of the tools I use to automate updating the infobox for open source project articles relies on the GitHub API to report the repository license and that requires a LICENSE file to parse. My bad about not double-checking that it used the correct license, I just pushed a commit to correct that.

**Comment by DanielOaks** [comment]
Ah fairfair, noice

**Comment by RogueScholar** [comment]
@davisonio Any chance of getting this PR reviewed? We're coming up on a couple months since it was submitted and I'd like to keep going with adding more icons to the listing but can't justify the time investment until I know that they'll be merged.

**Comment by davisonio** [comment]
Hey @RogueScholar thanks for this PR. Sorry this took so long to get merged, I must have missed this one! Love the icons and happy to merge in any more icons if you're happy to make them.

I've just merged this in with a few changes:
- keeping the case of contributing
- anchor link fix
- change Miscellaneous back (sorry but not sure many people know what Monotremes are!)
- not adding a code of content for now (I don't think they're useful)
- keeping badges to minimum and leaving out license file

**Comment by davisonio** [comment]
One other thing: can't seem to get the freenode awesome-irc link to show up... also hopefuly we'll get a few users there

**Pull request merged**
